# =============================================================================
# DEMO - Secrets Kubernetes pour OpenMetadata
# ATTENTION: Pour une d√©mo uniquement. Ne pas utiliser en production.
# =============================================================================

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: openmetadata
type: Opaque
stringData:
  openmetadata-mysql-password: "openmetadata_password"

---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  namespace: openmetadata
type: Opaque
stringData:
  openmetadata-airflow-password: "admin"

---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-secrets
  namespace: openmetadata
type: Opaque
stringData:
  openmetadata-elasticsearch-password: ""
